alias: Blood sugar check
description: Turn on the lights in the kitchen if my blood sugar drops low overnight
trigger:
  - platform: numeric_state
    entity_id: sensor.blood_glucose
    below: 75
condition:
  - condition: time
    after: "22:00:00"
    before: "06:00:00"
action:
  - service: light.turn_on
    data:
      brightness_pct: 26
    target:
      area_id: hallway
  - service: light.turn_on
    data:
      brightness: 65
    target:
      entity_id: light.south_light
  - service: tts.google_translate_say
    data:
      entity_id:
        - media_player.office_display
        - media_player.kitchen_display
        - media_player.living_room_speaker
        - media_player.master_bedroom_speaker
      message: Kid's blood sugar is {{states('sensor.blood_sugar')}}.
  - delay:
      hours: 0
      minutes: 5
      seconds: 0
      milliseconds: 0
mode: single
max_exceeded: silent
